@startuml

skinparam linetype ortho

artifact "ROR HealthcareService" as healthcareservice
artifact "ROR Location" as location
artifact "ROR Organization" as organization
artifact "ROR Practitioner" as practitioner
artifact "ROR PractitionerRole" as practitionerrole

url of healthcareservice [[StructureDefinition-ror-healthcareservice.html]]
url of location [[StructureDefinition-ror-location.html]]
url of organization [[StructureDefinition-ror-organization.html]]
url of practitioner [[StructureDefinition-ror-practitioner.html]]
url of practitionerrole [[StructureDefinition-ror-practitionerrole.html]]

' #############################
' # healthcareservice #
' #############################

' organization
healthcareservice --> organization : providedBy 0..1

' location
healthcareservice --> location : location 0..*

' ################
' # organization #
' ################
organization --> organization : partOf 0..1

' ####################
' # practitionerrole #
' ####################

' healthcareservice
practitionerrole --> healthcareservice : healthcareservice 1..1

' practitioner
practitionerrole --> practitioner : practitioner 1..1


@enduml