@startuml extraction_offre_partielle
actor "Consommateur" as C
actor "ROR national" as ROR
C -> ROR : Extraction_Offres \n (via critères de recherche)
ROR --> C : Réponse \n (attributs demandés des offres opérationnelles et les organisations liées)
@enduml
