@startuml maj_offre
actor "Serveur ou consommateur" as SC
actor "ROR national" as ROR
SC -> ROR : MiseAJour_Offre \n (via id + informations à modifier)
ROR --> SC : Réponse \n (id, identifiant fonctionnel et métadonnées)
@enduml

