@startuml recherche_consignes_fiche_saisie
actor "Consommateur" as C
actor "ROR national" as ROR
C -> ROR : Recherche_consignes_fiche_saisie \n (Recherche consignes fiche(s) de saisie)
ROR --> C : Réponse \n (Fiche(s) consignes de saisie)
@enduml