@startuml recherche_offre_donnees_capacitaires
actor "Consommateur" as C
actor "ROR national" as ROR
C -> ROR : Recherche_Offres \n (capacités des lieux de réalisation de l'offre via critères de recherche)
ROR --> C : Réponse \n (offres opérationnelles et tous les lieux de réalisation de l'offre liés)
@enduml
