@startuml recherche_modele_saisie
actor "Consommateur" as C
actor "ROR national" as ROR
C -> ROR : Recherche_modèle_de_saisie \n (Recherche modèle(s) de saisie)
ROR --> C : Réponse \n (Modèle(s) de saisie)
@enduml