@startuml recherche_offre_informations_tarifaires
actor "Consommateur" as C
actor "ROR national" as ROR
C -> ROR : Recherche_Offres \n (informations tarifaires via critères de recherche)
ROR --> C : Réponse \n (offres opérationnelles et lieux de réalisation de l'offre liés)
@enduml
