@startuml recherche_offre_criteres_principaux
actor "Consommateur" as C
actor "ROR national" as ROR
C -> ROR : Recherche_Offres \n (via critères de recherche)
ROR --> C : Réponse \n (offres opérationnelles et toutes les classes liées = tout le modèle d'exposition)
@enduml
