@startuml

'Declaration des éléments
rectangle "Vue fonctionnelle ROR" {

    rectangle "Offre opérationnelle" as Offre #LightSkyBlue;line:Black;text:Black

    rectangle "Entité juridique" as EJ #Gold;line:Black;text:Black

    rectangle "Entité géographique" as EG #Gold;line:Black;text:Black

    rectangle "Organisation interne" as OI #Gold;line:Black;text:Black
    
    rectangle "Lieu réalisation offre" as Lieu #Violet;line:Black;text:Black

    rectangle "Professionnel" as Professionnel #LimeGreen;line:Black;text:Black

    rectangle "Situation opérationnelle" as SO #LightSeaGreen;line:Black;text:Black

    rectangle "Exercice professionnel" as Ex  #LightSeaGreen;line:Black;text:Black

}

'Liens entre éléments
EJ "1"--"1..*" EG : "      " 
EG "1..*"-"*" OI : "          "
EG "0..1"--"*" Offre : "      "
OI "0..1"--"1..*" Offre
OI "0..1"-"*" OI
Offre "1..*"-"1..*" Lieu : "          "
SO "*"-"1" Offre
Ex "1"--"1..*" SO
Professionnel "1"--"1..*" Ex

'Légende

rectangle "Légende (Ressources FHIR)" #LightGrey {
    artifact "ROR HealthcareService" as healthcareservice #LightSkyBlue;line:Black;text:Black
    artifact "ROR Location" as location #Violet;line:Black;text:Black
    artifact "ROR Organization" as organization #Gold;line:Black;text:Black
    artifact "ROR Practitioner" as practitioner #LimeGreen;line:Black;text:Black
    artifact "ROR PractitionerRole" as practitionerrole #LightSeaGreen;line:black;text:Black
}

healthcareservice -[hidden]- organization
organization -[hidden]- location
location -[hidden]- practitioner
practitioner -[hidden]- practitionerrole

url of healthcareservice [[StructureDefinition-ror-healthcareservice.html]]
url of location [[StructureDefinition-ror-location.html]]
url of organization [[StructureDefinition-ror-organization.html]]
url of practitioner [[StructureDefinition-ror-practitioner.html]]
url of practitionerrole [[StructureDefinition-ror-practitionerrole.html]] 

@enduml


