name: Workflow   Tests/gitHubpages
on:
  workflow_call:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run-gitHubPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:      
          path: igSource

      - uses: ansforge/IG-workflows@v0.4.0

        with:      
          bake: "false"
          nos: "false"
          validator_cli: "true"     
          generate_plantuml : "true"
          repo_ig: "./igSource"   
          github_page: "true"
          github_page_token: ${{ secrets.ANS_IG_API_TOKEN  }}
